export const ADMIN_GET_PRODUCTS = "ADMIN_GET_PRODUCTS";
export const ADMIN_EDIT_PRODUCT = "ADMIN_EDIT_PRODUCT";
export const ADMIN_DELETE_PRODUCT = "ADMIN_DELETE_PRODUCT";
export const ADMIN_ADD_PRODUCT = "ADMIN_ADD_PRODUCT";

export const ADMIN_GET_BANNERS = "ADMIN_GET_PRODUCTS";
export const ADMIN_EDIT_BANNER = "ADMIN_EDIT_BANNER";
export const ADMIN_DELETE_BANNER = "ADMIN_DELETE_BANNER";
export const ADMIN_ADD_BANNER = "ADMIN_ADD_BANNER";

export const ADMIN_GET_STAFF_LIST = "ADMIN_GET_STAFF_LIST";

export const ADMIN_GET_CURRENT_USER = "ADMIN_GET_CURRENT_USER";

export const CUSTOMER_GET_PRODUCT = "CUSTOMER_GET_PRODUCT";
